### PR TITLE
children props should be typed as `ReactNode`

### PR DESCRIPTION
**Pull request by polamjag**
ref. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/41fe335d209b4cd46dedafd1a91849d7fec6880d/types/react/index.d.ts#L1218-L1222

## Description

`children` props of React Components should have type of `React.ReactNode`.

## Motivation and context

`children` of React Component may not only be Component but can be another forms, such as text node or else. 

FYI: definition of `Props` type in [@types/react](https://www.npmjs.com/package/@types/react) also types `children` as `ReactNode`.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/41fe335d209b4cd46dedafd1a91849d7fec6880d/types/react/index.d.ts#L1218-L1222

## How has this been tested?

Not tested well, but I think this change will not break anything.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

I think this is not breaking change because type `React.Node` accepts `React.Component`.

## Checklist:

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Rendez** [comment]
We're waiting for a release cut of the `spire` package so that our builds are green again, then I'll merge this PR.

**Comment by polamjag** [comment]
Thank you for your review! (And I'm sorry for leaving this p-r as WIP 🙇) 
I've updated p-r description a little to describe more details.

**Comment by danez** [comment]
Thanks again.

**Comment by polamjag** [comment]
Thank you too!

**Pull request merged**
