### PR TITLE
fix(observer): Fix#43 null children exception

### PR DESCRIPTION
**Pull request by 311289189**
Thanks for taking the time to file a pull request with us.
Please take a moment to provide the following details:

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ x] My code follows the code style of this project
- [ x] My change requires a change to the documentation
- [ x] I have updated the documentation accordingly
- [ x] I have read the [CONTRIBUTING](CONTRIBUTING.md) document
- [ x] I have added tests to cover my changes
- [ x] All new and existing tests passed

### CODE REVIEW

**Comment by 311289189** [comment]
#43

**Comment by Rendez** [comment]
Thank you! I just need a couple of days to review this since I'm quite busy atm.

**Comment by Rendez** [comment]
Alright, here's a few points of improvement:
- Adjust `types/index.d.ts` to make children optional.
- Return null in the render method method anything else.
- Allow to render children with `null` or `undefined` children for transparency: use `isDOMTypeElement` in the  IF condition.
- Do checking for target outside `observer.js`, so in the component instead for consistency.
- Do not remove a [value test case](https://github.com/researchgate/react-intersection-observer/pull/44/files#diff-e9db228c70df601d427dfbb8ebad9809L3).

**Comment by 311289189** [comment]
@Rendez thanks, I will get to it later

**Comment by 311289189** [comment]
Sorry I just didn't get time to address this

**Comment by Rendez** [comment]
@311289189 I released it under a `beta-0` tag. I'd appreciate if you could tell me if it solves your issue on your project. I'd plan to release it soon but I also didn't get the time to test it in our project. Cheers!

**Comment by 311289189** [comment]
Yes I just ran with the beta package and it works passing `null` or `undefined` and checked the commit in #52

**Pull request closed without merging**
